/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 06 10:08:59 CST 2019
 */

package test;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;

import java.util.List;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Main.readFileByLines((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<String> list0 = Main.readFileByLines("");
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Main.readFileByLines("relationTP_m.csv");
      // Undeclared exception!
      Main.readFileByLines("relationTP_m.csv");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      Main.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Main main0 = new Main();
      // Undeclared exception!
      try { 
        main0.readData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.Main", e);
      }
  }
}
