/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 07 17:10:41 CST 2019
 */

package test;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PasswordUtil_ESTest extends PasswordUtil_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 19 covered goals:
   * Goal 1. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false
   * Goal 2. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 3. [Output]: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:EmptyString
   * Goal 4. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 46
   * Goal 5. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 47
   * Goal 6. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 48
   * Goal 7. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 57
   * Goal 8. [METHOD] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 9. [METHODNOEX] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 10. Weak Mutation 58: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceConstant - 0 -> 1
   * Goal 11. Weak Mutation 129: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable i -> length
   * Goal 12. Weak Mutation 130: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of i
   * Goal 13. Weak Mutation 131: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 i
   * Goal 14. Weak Mutation 132: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 i
   * Goal 15. Weak Mutation 133: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable length -> i
   * Goal 16. Weak Mutation 134: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of length
   * Goal 17. Weak Mutation 135: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 length
   * Goal 18. Weak Mutation 136: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 length
   * Goal 19. Weak Mutation 137: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> !=
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = PasswordUtil.generateRandomString((-1));
      assertEquals("", string0);
  }

  //Test case number: 1
  /*
   * 62 covered goals:
   * Goal 1. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - true
   * Goal 2. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - false
   * Goal 3. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - true
   * Goal 4. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - false
   * Goal 5. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - true
   * Goal 6. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - false
   * Goal 7. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 8. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 9. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 10. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 11. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 12. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 13. [Output]: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:NonEmptyString
   * Goal 14. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 16
   * Goal 15. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 17
   * Goal 16. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 18
   * Goal 17. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 19
   * Goal 18. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 21
   * Goal 19. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 22
   * Goal 20. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 23
   * Goal 21. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 24
   * Goal 22. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 25
   * Goal 23. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 26
   * Goal 24. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 27
   * Goal 25. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 29
   * Goal 26. [METHOD] test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 27. [METHODNOEX] test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 28. Weak Mutation 0: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:17 - ReplaceConstant - MD5 -> 
   * Goal 29. Weak Mutation 1: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 30: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceVariable offset -> i
   * Goal 31. Weak Mutation 31: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp Negation of offset
   * Goal 32. Weak Mutation 32: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp IINC 1 offset
   * Goal 33. Weak Mutation 33: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp IINC -1 offset
   * Goal 34. Weak Mutation 35: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceComparisonOperator < -> -2
   * Goal 35. Weak Mutation 36: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceComparisonOperator < -> <=
   * Goal 36. Weak Mutation 2: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp Negation of offset
   * Goal 37. Weak Mutation 3: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp IINC 1 offset
   * Goal 38. Weak Mutation 4: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp IINC -1 offset
   * Goal 39. Weak Mutation 5: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceVariable i -> offset
   * Goal 40. Weak Mutation 6: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp Negation of i
   * Goal 41. Weak Mutation 7: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp IINC 1 i
   * Goal 42. Weak Mutation 8: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp IINC -1 i
   * Goal 43. Weak Mutation 9: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceComparisonOperator >= -> -1
   * Goal 44. Weak Mutation 10: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceComparisonOperator >= -> ==
   * Goal 45. Weak Mutation 12: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:24 - ReplaceVariable i -> offset
   * Goal 46. Weak Mutation 13: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceVariable i -> offset
   * Goal 47. Weak Mutation 14: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp Negation of i
   * Goal 48. Weak Mutation 15: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp IINC 1 i
   * Goal 49. Weak Mutation 16: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp IINC -1 i
   * Goal 50. Weak Mutation 17: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 0
   * Goal 51. Weak Mutation 18: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 1
   * Goal 52. Weak Mutation 19: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> -1
   * Goal 53. Weak Mutation 20: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 15
   * Goal 54. Weak Mutation 21: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 17
   * Goal 55. Weak Mutation 22: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceComparisonOperator >= -> -1
   * Goal 56. Weak Mutation 23: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceComparisonOperator >= -> >
   * Goal 57. Weak Mutation 24: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceComparisonOperator >= -> ==
   * Goal 58. Weak Mutation 25: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:26 - ReplaceConstant - 0 -> 
   * Goal 59. Weak Mutation 26: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - ReplaceVariable i -> offset
   * Goal 60. Weak Mutation 27: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp Negation of i
   * Goal 61. Weak Mutation 28: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp IINC 1 i
   * Goal 62. Weak Mutation 29: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = PasswordUtil.MD5("43bT1");
      assertEquals("28ef181130682efcaa29c20810822eb2", string0);
  }

  //Test case number: 2
  /*
   * 17 covered goals:
   * Goal 1. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false
   * Goal 2. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 3. [Output]: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:EmptyString
   * Goal 4. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 46
   * Goal 5. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 47
   * Goal 6. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 48
   * Goal 7. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 57
   * Goal 8. [METHOD] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 9. [METHODNOEX] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 10. Weak Mutation 58: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceConstant - 0 -> 1
   * Goal 11. Weak Mutation 130: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of i
   * Goal 12. Weak Mutation 131: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 i
   * Goal 13. Weak Mutation 132: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 i
   * Goal 14. Weak Mutation 134: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of length
   * Goal 15. Weak Mutation 135: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 length
   * Goal 16. Weak Mutation 136: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 length
   * Goal 17. Weak Mutation 139: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> <=
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = PasswordUtil.generateRandomString(0);
      assertEquals("", string0);
  }

  //Test case number: 3
  /*
   * 15 covered goals:
   * Goal 1. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - false
   * Goal 2. Branch test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - false in context: test.PasswordUtil:convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 3. [Output]: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:EmptyString
   * Goal 4. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 36
   * Goal 5. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 37
   * Goal 6. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 40
   * Goal 7. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 41
   * Goal 8. [METHOD] test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 9. [METHODNOEX] test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 10. Weak Mutation 37: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - ReplaceConstant - 0 -> 1
   * Goal 11. Weak Mutation 51: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp Negation of i
   * Goal 12. Weak Mutation 52: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp IINC 1 i
   * Goal 13. Weak Mutation 53: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp IINC -1 i
   * Goal 14. Weak Mutation 56: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - ReplaceComparisonOperator < -> <=
   * Goal 15. Weak Mutation 57: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:41 - ReplaceVariable s -> str
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = PasswordUtil.convertMD5("");
      assertEquals("", string0);
  }

  //Test case number: 4
  /*
   * 111 covered goals:
   * Goal 1. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - true
   * Goal 2. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false
   * Goal 3. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - true
   * Goal 4. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - false
   * Goal 5. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - true
   * Goal 6. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - false
   * Goal 7. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - true
   * Goal 8. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - false
   * Goal 9. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I73 Branch 8 IFEQ L53 - false
   * Goal 10. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 11. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 12. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 13. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 14. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 15. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 16. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 17. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 18. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I73 Branch 8 IFEQ L53 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 19. generateRandomString(I)Ljava/lang/String;_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 20. [Output]: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:NonEmptyString
   * Goal 21. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 46
   * Goal 22. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 47
   * Goal 23. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 48
   * Goal 24. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 49
   * Goal 25. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 50
   * Goal 26. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 51
   * Goal 27. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 52
   * Goal 28. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 53
   * Goal 29. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 54
   * Goal 30. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 57
   * Goal 31. [METHOD] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 32. [METHODNOEX] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 33. Weak Mutation 58: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceConstant - 0 -> 1
   * Goal 34. Weak Mutation 128: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable i -> length
   * Goal 35. Weak Mutation 129: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable i -> length
   * Goal 36. Weak Mutation 130: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of i
   * Goal 37. Weak Mutation 131: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 i
   * Goal 38. Weak Mutation 132: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 i
   * Goal 39. Weak Mutation 133: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable length -> i
   * Goal 40. Weak Mutation 134: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of length
   * Goal 41. Weak Mutation 135: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 length
   * Goal 42. Weak Mutation 136: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 length
   * Goal 43. Weak Mutation 138: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> -2
   * Goal 44. Weak Mutation 139: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> <=
   * Goal 45. Weak Mutation 59: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 0
   * Goal 46. Weak Mutation 60: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 1
   * Goal 47. Weak Mutation 61: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> -1
   * Goal 48. Weak Mutation 62: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 3
   * Goal 49. Weak Mutation 63: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 0
   * Goal 50. Weak Mutation 64: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 1
   * Goal 51. Weak Mutation 65: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> -1
   * Goal 52. Weak Mutation 66: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 3
   * Goal 53. Weak Mutation 67: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> +
   * Goal 54. Weak Mutation 68: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> -
   * Goal 55. Weak Mutation 69: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> *
   * Goal 56. Weak Mutation 70: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> /
   * Goal 57. Weak Mutation 71: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceComparisonOperator != -> -1
   * Goal 58. Weak Mutation 72: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceComparisonOperator != -> <
   * Goal 59. Weak Mutation 74: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - char -> 
   * Goal 60. Weak Mutation 75: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - num -> 
   * Goal 61. Weak Mutation 76: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceConstant - char -> 
   * Goal 62. Weak Mutation 77: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceVariable charOrNum -> val
   * Goal 63. Weak Mutation 78: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceComparisonOperator == -> !=
   * Goal 64. Weak Mutation 79: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 0
   * Goal 65. Weak Mutation 80: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 1
   * Goal 66. Weak Mutation 81: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> -1
   * Goal 67. Weak Mutation 82: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 3
   * Goal 68. Weak Mutation 83: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 0
   * Goal 69. Weak Mutation 84: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 1
   * Goal 70. Weak Mutation 85: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> -1
   * Goal 71. Weak Mutation 86: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 3
   * Goal 72. Weak Mutation 87: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> +
   * Goal 73. Weak Mutation 88: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> -
   * Goal 74. Weak Mutation 89: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> *
   * Goal 75. Weak Mutation 90: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> /
   * Goal 76. Weak Mutation 91: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceComparisonOperator != -> -1
   * Goal 77. Weak Mutation 92: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceComparisonOperator != -> <
   * Goal 78. Weak Mutation 94: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 0
   * Goal 79. Weak Mutation 95: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 1
   * Goal 80. Weak Mutation 96: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> -1
   * Goal 81. Weak Mutation 97: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 64
   * Goal 82. Weak Mutation 98: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 66
   * Goal 83. Weak Mutation 99: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 0
   * Goal 84. Weak Mutation 100: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 1
   * Goal 85. Weak Mutation 101: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> -1
   * Goal 86. Weak Mutation 102: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 96
   * Goal 87. Weak Mutation 103: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 98
   * Goal 88. Weak Mutation 104: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable val -> charOrNum
   * Goal 89. Weak Mutation 105: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 0
   * Goal 90. Weak Mutation 106: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 1
   * Goal 91. Weak Mutation 107: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> -1
   * Goal 92. Weak Mutation 108: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 25
   * Goal 93. Weak Mutation 109: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 27
   * Goal 94. Weak Mutation 110: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable temp -> length
   * Goal 95. Weak Mutation 111: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable temp -> i
   * Goal 96. Weak Mutation 112: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp Negation of temp
   * Goal 97. Weak Mutation 113: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp IINC 1 temp
   * Goal 98. Weak Mutation 114: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp IINC -1 temp
   * Goal 99. Weak Mutation 115: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> %
   * Goal 100. Weak Mutation 116: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> -
   * Goal 101. Weak Mutation 117: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> *
   * Goal 102. Weak Mutation 118: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> /
   * Goal 103. Weak Mutation 119: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceConstant - num -> 
   * Goal 104. Weak Mutation 120: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceVariable charOrNum -> val
   * Goal 105. Weak Mutation 121: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceComparisonOperator == -> !=
   * Goal 106. Weak Mutation 122: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceVariable val -> charOrNum
   * Goal 107. Weak Mutation 123: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 0
   * Goal 108. Weak Mutation 124: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 1
   * Goal 109. Weak Mutation 125: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> -1
   * Goal 110. Weak Mutation 126: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 9
   * Goal 111. Weak Mutation 127: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 11
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PasswordUtil.generateRandomString(2154);
      PasswordUtil.generateRandomString(2614);
      PasswordUtil.generateRandomString(2614);
      // Undeclared exception!
      PasswordUtil.generateRandomString(2614);
  }

  //Test case number: 5
  /*
   * 143 covered goals:
   * Goal 1. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - true
   * Goal 2. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - false
   * Goal 3. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - true
   * Goal 4. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false
   * Goal 5. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - true
   * Goal 6. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - false
   * Goal 7. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - true
   * Goal 8. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - false
   * Goal 9. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - true
   * Goal 10. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - false
   * Goal 11. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I73 Branch 8 IFEQ L53 - false
   * Goal 12. Branch test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - false in context: test.PasswordUtil:convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 13. Branch test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: I29 Branch 4 IF_ICMPLT L37 - true in context: test.PasswordUtil:convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 14. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 15. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I94 Branch 9 IF_ICMPLT L48 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 16. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 17. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I23 Branch 5 IFNE L49 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 18. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 19. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I35 Branch 6 IFEQ L50 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 20. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 21. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I43 Branch 7 IFNE L51 - true in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 22. Branch test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: I73 Branch 8 IFEQ L53 - false in context: test.PasswordUtil:generateRandomString(I)Ljava/lang/String;
   * Goal 23. convertMD5(Ljava/lang/String;)Ljava/lang/String;_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 24. [Output]: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:NonEmptyString
   * Goal 25. [Output]: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:NonEmptyString
   * Goal 26. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 36
   * Goal 27. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 37
   * Goal 28. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 38
   * Goal 29. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 40
   * Goal 30. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 41
   * Goal 31. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 46
   * Goal 32. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 47
   * Goal 33. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 48
   * Goal 34. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 49
   * Goal 35. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 50
   * Goal 36. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 51
   * Goal 37. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 52
   * Goal 38. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 53
   * Goal 39. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 54
   * Goal 40. test.PasswordUtil.generateRandomString(I)Ljava/lang/String;: Line 57
   * Goal 41. [METHOD] test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 42. [METHOD] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 43. [METHODNOEX] test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 44. [METHODNOEX] test.PasswordUtil.generateRandomString(I)Ljava/lang/String;
   * Goal 45. Weak Mutation 37: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - ReplaceConstant - 0 -> 1
   * Goal 46. Weak Mutation 51: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp Negation of i
   * Goal 47. Weak Mutation 52: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp IINC 1 i
   * Goal 48. Weak Mutation 53: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - InsertUnaryOp IINC -1 i
   * Goal 49. Weak Mutation 55: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - ReplaceComparisonOperator < -> -2
   * Goal 50. Weak Mutation 56: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:37 - ReplaceComparisonOperator < -> <=
   * Goal 51. Weak Mutation 38: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp Negation of i
   * Goal 52. Weak Mutation 39: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp IINC 1 i
   * Goal 53. Weak Mutation 40: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp IINC -1 i
   * Goal 54. Weak Mutation 41: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp Negation of i
   * Goal 55. Weak Mutation 42: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp IINC 1 i
   * Goal 56. Weak Mutation 43: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - InsertUnaryOp IINC -1 i
   * Goal 57. Weak Mutation 44: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceConstant - 116 -> 0
   * Goal 58. Weak Mutation 45: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceConstant - 116 -> 1
   * Goal 59. Weak Mutation 46: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceConstant - 116 -> -1
   * Goal 60. Weak Mutation 47: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceConstant - 116 -> 115
   * Goal 61. Weak Mutation 48: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceConstant - 116 -> 117
   * Goal 62. Weak Mutation 49: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceBitwiseOperator ^ -> |
   * Goal 63. Weak Mutation 50: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:38 - ReplaceBitwiseOperator ^ -> &
   * Goal 64. Weak Mutation 57: test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;:41 - ReplaceVariable s -> str
   * Goal 65. Weak Mutation 58: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceConstant - 0 -> 1
   * Goal 66. Weak Mutation 128: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable i -> length
   * Goal 67. Weak Mutation 129: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable i -> length
   * Goal 68. Weak Mutation 130: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of i
   * Goal 69. Weak Mutation 131: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 i
   * Goal 70. Weak Mutation 132: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 i
   * Goal 71. Weak Mutation 133: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceVariable length -> i
   * Goal 72. Weak Mutation 134: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp Negation of length
   * Goal 73. Weak Mutation 135: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC 1 length
   * Goal 74. Weak Mutation 136: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - InsertUnaryOp IINC -1 length
   * Goal 75. Weak Mutation 138: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> -2
   * Goal 76. Weak Mutation 139: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:48 - ReplaceComparisonOperator < -> <=
   * Goal 77. Weak Mutation 59: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 0
   * Goal 78. Weak Mutation 60: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 1
   * Goal 79. Weak Mutation 61: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> -1
   * Goal 80. Weak Mutation 62: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 3
   * Goal 81. Weak Mutation 63: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 0
   * Goal 82. Weak Mutation 64: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 1
   * Goal 83. Weak Mutation 65: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> -1
   * Goal 84. Weak Mutation 66: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - 2 -> 3
   * Goal 85. Weak Mutation 67: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> +
   * Goal 86. Weak Mutation 68: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> -
   * Goal 87. Weak Mutation 69: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> *
   * Goal 88. Weak Mutation 70: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceArithmeticOperator % -> /
   * Goal 89. Weak Mutation 71: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceComparisonOperator != -> -1
   * Goal 90. Weak Mutation 72: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceComparisonOperator != -> <
   * Goal 91. Weak Mutation 74: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - char -> 
   * Goal 92. Weak Mutation 75: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:49 - ReplaceConstant - num -> 
   * Goal 93. Weak Mutation 76: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceConstant - char -> 
   * Goal 94. Weak Mutation 77: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceVariable charOrNum -> val
   * Goal 95. Weak Mutation 78: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:50 - ReplaceComparisonOperator == -> !=
   * Goal 96. Weak Mutation 79: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 0
   * Goal 97. Weak Mutation 80: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 1
   * Goal 98. Weak Mutation 81: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> -1
   * Goal 99. Weak Mutation 82: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 3
   * Goal 100. Weak Mutation 83: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 0
   * Goal 101. Weak Mutation 84: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 1
   * Goal 102. Weak Mutation 85: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> -1
   * Goal 103. Weak Mutation 86: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 2 -> 3
   * Goal 104. Weak Mutation 87: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> +
   * Goal 105. Weak Mutation 88: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> -
   * Goal 106. Weak Mutation 89: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> *
   * Goal 107. Weak Mutation 90: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceArithmeticOperator % -> /
   * Goal 108. Weak Mutation 91: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceComparisonOperator != -> -1
   * Goal 109. Weak Mutation 92: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceComparisonOperator != -> <
   * Goal 110. Weak Mutation 94: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 0
   * Goal 111. Weak Mutation 95: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 1
   * Goal 112. Weak Mutation 96: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> -1
   * Goal 113. Weak Mutation 97: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 64
   * Goal 114. Weak Mutation 98: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 65 -> 66
   * Goal 115. Weak Mutation 99: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 0
   * Goal 116. Weak Mutation 100: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 1
   * Goal 117. Weak Mutation 101: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> -1
   * Goal 118. Weak Mutation 102: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 96
   * Goal 119. Weak Mutation 103: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:51 - ReplaceConstant - 97 -> 98
   * Goal 120. Weak Mutation 104: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable val -> charOrNum
   * Goal 121. Weak Mutation 105: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 0
   * Goal 122. Weak Mutation 106: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 1
   * Goal 123. Weak Mutation 107: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> -1
   * Goal 124. Weak Mutation 108: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 25
   * Goal 125. Weak Mutation 109: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceConstant - 26 -> 27
   * Goal 126. Weak Mutation 110: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable temp -> length
   * Goal 127. Weak Mutation 111: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceVariable temp -> i
   * Goal 128. Weak Mutation 112: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp Negation of temp
   * Goal 129. Weak Mutation 113: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp IINC 1 temp
   * Goal 130. Weak Mutation 114: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - InsertUnaryOp IINC -1 temp
   * Goal 131. Weak Mutation 115: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> %
   * Goal 132. Weak Mutation 116: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> -
   * Goal 133. Weak Mutation 117: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> *
   * Goal 134. Weak Mutation 118: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:52 - ReplaceArithmeticOperator + -> /
   * Goal 135. Weak Mutation 119: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceConstant - num -> 
   * Goal 136. Weak Mutation 120: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceVariable charOrNum -> val
   * Goal 137. Weak Mutation 121: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:53 - ReplaceComparisonOperator == -> !=
   * Goal 138. Weak Mutation 122: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceVariable val -> charOrNum
   * Goal 139. Weak Mutation 123: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 0
   * Goal 140. Weak Mutation 124: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 1
   * Goal 141. Weak Mutation 125: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> -1
   * Goal 142. Weak Mutation 126: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 9
   * Goal 143. Weak Mutation 127: test.PasswordUtil.generateRandomString(I)Ljava/lang/String;:54 - ReplaceConstant - 10 -> 11
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = PasswordUtil.generateRandomString(2499);
      String string1 = PasswordUtil.convertMD5(string0);
      PasswordUtil.convertMD5(string0);
      PasswordUtil.convertMD5(string0);
      // Undeclared exception!
      PasswordUtil.convertMD5(string1);
  }

  //Test case number: 6
  /*
   * 4 covered goals:
   * Goal 1. convertMD5(Ljava/lang/String;)Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: Line 36
   * Goal 3. test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * Goal 4. [METHOD] test.PasswordUtil.convertMD5(Ljava/lang/String;)Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        PasswordUtil.convertMD5((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.PasswordUtil", e);
      }
  }

  //Test case number: 7
  /*
   * 7 covered goals:
   * Goal 1. MD5(Ljava/lang/String;)Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 16
   * Goal 3. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 17
   * Goal 4. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 18
   * Goal 5. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * Goal 6. [METHOD] test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 7. Weak Mutation 0: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:17 - ReplaceConstant - MD5 -> 
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        PasswordUtil.MD5((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.PasswordUtil", e);
      }
  }

  //Test case number: 8
  /*
   * 62 covered goals:
   * Goal 1. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - true
   * Goal 2. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - false
   * Goal 3. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - true
   * Goal 4. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - false
   * Goal 5. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - true
   * Goal 6. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - false
   * Goal 7. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 8. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I66 Branch 3 IF_ICMPLT L21 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 9. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 10. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 1 IFGE L23 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 11. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - false in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 12. Branch test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: I45 Branch 2 IF_ICMPGE L25 - true in context: test.PasswordUtil:MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 13. [Output]: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:NonEmptyString
   * Goal 14. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 16
   * Goal 15. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 17
   * Goal 16. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 18
   * Goal 17. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 19
   * Goal 18. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 21
   * Goal 19. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 22
   * Goal 20. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 23
   * Goal 21. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 24
   * Goal 22. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 25
   * Goal 23. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 26
   * Goal 24. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 27
   * Goal 25. test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;: Line 29
   * Goal 26. [METHOD] test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 27. [METHODNOEX] test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;
   * Goal 28. Weak Mutation 0: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:17 - ReplaceConstant - MD5 -> 
   * Goal 29. Weak Mutation 1: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 30: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceVariable offset -> i
   * Goal 31. Weak Mutation 31: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp Negation of offset
   * Goal 32. Weak Mutation 32: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp IINC 1 offset
   * Goal 33. Weak Mutation 33: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - InsertUnaryOp IINC -1 offset
   * Goal 34. Weak Mutation 35: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceComparisonOperator < -> -2
   * Goal 35. Weak Mutation 36: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:21 - ReplaceComparisonOperator < -> <=
   * Goal 36. Weak Mutation 2: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp Negation of offset
   * Goal 37. Weak Mutation 3: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp IINC 1 offset
   * Goal 38. Weak Mutation 4: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:22 - InsertUnaryOp IINC -1 offset
   * Goal 39. Weak Mutation 5: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceVariable i -> offset
   * Goal 40. Weak Mutation 6: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp Negation of i
   * Goal 41. Weak Mutation 7: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp IINC 1 i
   * Goal 42. Weak Mutation 8: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - InsertUnaryOp IINC -1 i
   * Goal 43. Weak Mutation 9: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceComparisonOperator >= -> -1
   * Goal 44. Weak Mutation 10: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceComparisonOperator >= -> ==
   * Goal 45. Weak Mutation 11: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:23 - ReplaceComparisonOperator >= -> >
   * Goal 46. Weak Mutation 12: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:24 - ReplaceVariable i -> offset
   * Goal 47. Weak Mutation 13: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceVariable i -> offset
   * Goal 48. Weak Mutation 14: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp Negation of i
   * Goal 49. Weak Mutation 15: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp IINC 1 i
   * Goal 50. Weak Mutation 16: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - InsertUnaryOp IINC -1 i
   * Goal 51. Weak Mutation 17: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 0
   * Goal 52. Weak Mutation 18: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 1
   * Goal 53. Weak Mutation 19: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> -1
   * Goal 54. Weak Mutation 20: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 15
   * Goal 55. Weak Mutation 21: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceConstant - 16 -> 17
   * Goal 56. Weak Mutation 22: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceComparisonOperator >= -> -1
   * Goal 57. Weak Mutation 24: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:25 - ReplaceComparisonOperator >= -> ==
   * Goal 58. Weak Mutation 25: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:26 - ReplaceConstant - 0 -> 
   * Goal 59. Weak Mutation 26: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - ReplaceVariable i -> offset
   * Goal 60. Weak Mutation 27: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp Negation of i
   * Goal 61. Weak Mutation 28: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp IINC 1 i
   * Goal 62. Weak Mutation 29: test.PasswordUtil.MD5(Ljava/lang/String;)Ljava/lang/String;:27 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = PasswordUtil.MD5("");
      assertEquals("d41d8cd98f00b204e9800998ecf8427e", string0);
  }

  //Test case number: 9
  /*
   * 5 covered goals:
   * Goal 1. test.PasswordUtil.<init>()V: root-Branch
   * Goal 2. Branch test.PasswordUtil.<init>()V: root-Branch in context: test.PasswordUtil:<init>()V
   * Goal 3. test.PasswordUtil.<init>()V: Line 12
   * Goal 4. [METHOD] test.PasswordUtil.<init>()V
   * Goal 5. [METHODNOEX] test.PasswordUtil.<init>()V
   */

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      PasswordUtil passwordUtil0 = new PasswordUtil();
  }
}
